spring.application.name=cierre-bancario-batch
spring.datasource.url=jdbc:mysql://localhost:3306/banco_db
spring.datasource.username=academia
spring.datasource.password=academia123
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
